apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-backend
  template:
    metadata:
      labels:
        app: library-backend
    spec:
      containers:
        - name: library-backend
          image: savanvairagi123/library-backend:v1.2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -Xms256m -Xmx512m"
            - name: SPRING_APPLICATION_NAME
              value: "library"
            - name: SERVER_PORT
              value: "8080"
            - name: APP_CORS_ORIGINS
              value: "http://localhost:4200"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:library_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.h2.Driver"
            - name: SPRING_H2_CONSOLE_ENABLED
              value: "true"
            - name: SPRING_H2_CONSOLE_PATH
              value: "/h2-console"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "create-drop"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
            - name: SPRING_JPA_OPEN_IN_VIEW
              value: "false"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.H2Dialect"
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
